---
title: "Thesis on Open Sciene and data - Title WIP"
author: "Raoul Bruens"
toc: true
number-sections: true
highlight-style: pygments
format: 
  html: 
    code-fold: true
    html-math-method: katex
  pdf: 
    geometry: 
      - top=30mm
      - left=20mm
  docx: default
bibliography: references.bib
reference-location: margin
jupyter: python3
---

_Showing version from branch `first-text`_

## Abstract {.unnumbered}
Lorum ipsum.

## Introduction
With the ongoing advancements in AI and computer science, more and more applications will incorporate use cases of these technologies. It is not at all uncommon to see AI or other algorithmic solutions being used in business or society. For one, the results of a particular deicision-making algorithm or computer model can be used to establish certain policies. However, in a social or political context, this is not always done in a standardized, constructive, or transparent way. This can sometimes lead to ignorance, misconduct or even abuse when it comes down to executing such a policy. Subsequently, if something goes wrong, finding out what went wrong and potentially rectifying the problem can be a costly endeavor. What's more, such breaches can result in a degree of culpability or persuasion of legal action.

This research document provides an overview of several relevant topics, areas and projects that illustrate or support the need for an open view of processes, with a focus on processes involving (public) data. It also highlights several principles that will support a [framework/set of requirements] for a process to mitigate the risk of bias, misconduct and ambiguity and to maximize stakeholder participation, process transparency, and traceability of decisions. In the end, this [framework/set of requirements] is validated through a presentation of a proof of concept that substantiates the intended purposes.

{{< include chapters/1_open_science.qmd >}}

{{< include chapters/2_robust_incident.qmd >}}

{{< include chapters/3_data_science_steps.qmd >}}

{{< include chapters/4_requirements.qmd >}}

{{< include chapters/5_application.qmd >}}

{{< include chapters/6_proof_of_concept.qmd >}}

{{< include chapters/7_results.qmd >}}


